[package]
name = "bud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
rand = "0.8.4"
image = "0.23"
derive_deref = "1.1.1"
